#!/usr/bin/env bash
#
# Set standard bash safeguards
set -euo pipefail

# Load the asset environment variables (eg. JRE_FILENAME, JRE_URL, JRE_VERSION)
source ./assets-info.env

# Remove all the assets
rm -rf ./assets/
mkdir ./assets

# Download assets
wget -P assets $MSMPI_URL 
wget -P assets $JRE_URL

# Unzip the jre to its directory and remove their original zip
cd assets
JRE_DIR=jre
mkdir $JRE_DIR
JRE_FILENAME=$(basename $JRE_URL)
mv $JRE_FILENAME $JRE_DIR
cd $JRE_DIR
tar xzvf $JRE_FILENAME
rm -f $JRE_FILENAME
cd ..

# Success message for the user
echo "All assets downloaded!"
